src/main/java/webapp/runner/launch/CommandLineParams.java
src/main/java/webapp/runner/launch/Main.java
src/test/java/webapp/runner/launch/TomcatBaseDirResolutionTest.java

Hi people!
I wold like to choose the temp directory, this features is complete and tested!
Thanks!

adding temp directory parameter feature

---

README.md
src/main/java/webapp/runner/launch/CommandLineParams.java
src/main/java/webapp/runner/launch/Main.java

Add support for running behind a proxy with --proxy-base-url option

---

pom.xml
src/main/java/webapp/runner/launch/CommandLineParams.java
src/main/java/webapp/runner/launch/Main.java

Allows to set HTTP Connector Attributes.
[https://tomcat.apache.org/tomcat-8.0-doc/config/http.html](https://tomcat.apache.org/tomcat-8.0-doc/config/http.html)
Usage:
```java -jar webapp-runner.jar <main class> -Acompression=on -AcompressionMinSize=1024 -A_any_other_connector_property=value```

Allows to set HTTP Connector Attributes

---

src/main/java/webapp/runner/launch/MemcacheSessionStore.java

Hello, just noticed these lines were missing and figured I'd add them instead of having to manually workaround it setting memcachedcloud env variables as memcachier ones

Add Memcached Cloud support to MemcacheSessionStore

---

src/main/java/webapp/runner/launch/CommandLineParams.java
src/main/java/webapp/runner/launch/Main.java

Fixes Issue #57 by adding absolute dir capability

---

src/main/java/webapp/runner/launch/Main.java

Thanks for accepting #77 - this is a cherry picked commit of the same (as I need Tomcat 8 🥇 )

Fix issue with --proxy-base-url not being set to the provided hostname

---

README.md
main/src/main/java/webapp/runner/launch/CommandLineParams.java
memcached/src/main/java/webapp/runner/launch/MemcacheSessionStore.java

Adds ability to override default transcoder used.

TranscoderFactoryClass Support

---

README.md
assembly/pom.xml
assembly/src/it/heroku-maven-plugin/pom.xml
assembly/src/it/memcache-test/pom.xml
assembly/src/it/single_webapp/pom.xml
main/pom.xml
memcached/pom.xml
pom.xml
redis/pom.xml

~Tests are currently broken, waits on https://github.com/heroku/heroku-maven-plugin/pull/52~

Update groupid and docs to com.heroku (master)

---

assembly/pom.xml
main/pom.xml
memcached/pom.xml
pom.xml
redis/pom.xml

Our first release under `com.heroku` 🎉

Bump Tomcat to 8.5.50

---

assembly/pom.xml
main/pom.xml
memcached/pom.xml
pom.xml
redis/pom.xml

The last release was missing this version bump.

Bump version to 8.5.57.1-SNAPSHOT

---

pom.xml

Tomcat changelog here: http://tomcat.apache.org/tomcat-9.0-doc/changelog.html#Tomcat_9.0.38_(markt)

Update to Tomcat 9.0.38

---

assembly/pom.xml
main/pom.xml
memcached/pom.xml
pom.xml
redis/pom.xml

Bump Tomcat version to 9.0.41
Coses [W-8493176](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008k1GlIAI/view)

Tomcat 9.0.41

---

assembly/pom.xml
main/pom.xml
memcached/pom.xml
pom.xml
redis/pom.xml

Bump Tomcat version to 8.5.61
Coses [W-8493176](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008k1GlIAI/view)

Tomcat 8.5.61

---

assembly/pom.xml
assembly/src/it/single_webapp/verify.groovy
main/pom.xml
memcached/pom.xml
pom.xml
redis/pom.xml

Sub pom.xml files need to be updated in addition to the top level https://github.com/heroku/webapp-runner/pull/224.

Update Tomcat 8.5 to latest patch release 8.5.68

---

.circleci/config.yml
scripts/check-version.sh

Copy of #228 for Tomcat 9
References GUS-W-9802671

Add CI check for version consistency (Tomcat 9)

---

assembly/pom.xml
main/pom.xml
memcached/pom.xml
pom.xml
redis/pom.xml

Upgrades Tomcat to `9.0.68`.
Closes GUS-W-11938752

Tomcat 9.0.68

---

pom.xml
webapp-runner-main/pom.xml
webapp-runner-memcached/pom.xml
webapp-runner-redis/pom.xml
webapp-runner/pom.xml

Update to Tomcat 9.0.69

---

pom.xml
webapp-runner-main/pom.xml
webapp-runner-memcached/pom.xml
webapp-runner-redis/pom.xml
webapp-runner/pom.xml

Perform post-release operations after 9.0.69.0

---

pom.xml
webapp-runner-main/pom.xml
webapp-runner-memcached/pom.xml
webapp-runner-redis/pom.xml
webapp-runner/pom.xml

Perform post-release operations after 9.0.70.0

---

pom.xml
webapp-runner-main/pom.xml
webapp-runner-memcached/pom.xml
webapp-runner-redis/pom.xml
webapp-runner/pom.xml

Perform post-release operations after 9.0.71.0

---

pom.xml
webapp-runner-main/pom.xml
webapp-runner-memcached/pom.xml
webapp-runner-redis/pom.xml
webapp-runner/pom.xml

Prepare for next version

---

.github/dependabot.yml
.github/workflows/check_changelog.yml
.github/workflows/prepare-release.yml
CHANGELOG.md

Add prepare release workflow, actual release workflow will be added in a separate PR. This PR also adds a CHANGELOG for the first time which will also be updated by the prepare release automation.
Ref: GUS-W-14234076

Add prepare release workflow and changelog

---

.github/workflows/release.yml
CHANGELOG.md

Minor release and CHANGELOG fixes

---

.github/workflows/prepare-release.yml
.github/workflows/release.yml

Fix release automation
