- .gitignore
- README.md
- pom.xml
Apache Tomcat 8.5.x is intended to replace 8.0.x and includes new features pulled forward from Tomcat 9.0.x. All dependencies have been upgraded and the minimum Java version is Java 7 (for maven-compiler-plugin). Project version is now 8.5.5.0-SNAPSHOT.
> Upgrade Tomcat to 8.5

- src/main/java/webapp/runner/launch/CommandLineParams.java
Hi, I've tried without success to set the "--bind-on-init" parameter to false. The problem is associated with 
JCommander boolean values with default value equal to true. Here's an excerpt from [JCommand doc](http://jcommander.org/#Types_of_options) about boolean types:
If you want to define a boolean parameter that's true by default, you can declare it as having an arity of 1. Users will then have to specify the value they want explicitly:
```java
@Parameter(names = "-debug", description = "Debug mode", arity = 1)
private boolean debug = true;
```
Invoke with either of:
```java
program -debug true
program -debug false
```
I did a debugging session the application locally and now it seems to behave fine.
> Add arity option to boolean parameters with TRUE as default value

- main/src/main/java/webapp/runner/launch/Main.java
When running behind a proxy, the URL resolution was always being returned as `localhost:<proxy port`.
e.g. passing `--proxy-base-url https://some-domain:3000` would be setup as `localhost:3000`
This fixes the issue by setting the proxy name to the provided URI's host value.
> Fix issue with --proxy-base-url not being set to the provided hostname

- README.md
- main/src/main/java/webapp/runner/launch/CommandLineParams.java
- memcached/src/main/java/webapp/runner/launch/MemcacheSessionStore.java
I made some adjustments to PR #83 including:
* Change the name of the param to `--memcached-transcoder-factory-class` so the scope is clear to people reading the docs (our other params start with `--session-store`, but really should start wil `--memcached`, but that's because they came before Redis support. le sigh).
* Change the default value of the param to `null`, and don't do anything if it hasn't been set. This will ensure that nothing breaks unexpectedly, but also makes sure the defaults still work when we upgrade memcached-session-manager.
@jaGarcia please review my changes and make sure they are acceptable for you.
> Memcached transcoder factory class

- pom.xml
- redis/src/main/java/webapp/runner/launch/RedisSessionStore.java
Fix: https://github.com/jsimone/webapp-runner/issues/126
FstCodec is the default for redisson according to the wiki. Before
webapp-runner would default to JsonJacksonCodec.
A better solution might be to make this config a command line argument. Though in that case it might be preferred to create a new command line argument that feeds the whole redisson config json instead.
> Use FstCodec for redis + upgrade redisson 3.10.0

- main/pom.xml
- main/src/assembly/jar-with-deps-merge-services.xml
Fix for issue #99 
The problem is standalone Tomcat has multiple jars and two of them has `META-INF/services/javax.servlet.ServletContainerInitializer` file. That file contains classes that will be initialized on Tomcat startup. In `webapp-runner.jar` that file overwritten and includes only `org.apache.jasper.servlet.JasperInitializer`. For Websockets availability it must include also `org.apache.tomcat.websocket.server.WsSci` class.
PR fixes assembly configuration for merging META-INF/services.
> Fix Tomcat Websocket failure

- main/src/test/java/webapp/runner/launch/TomcatBaseDirResolutionTest.java
> Use platform specific path separators in tests

- main/src/test/java/webapp/runner/launch/TomcatBaseDirResolutionTest.java
> Use platform specific path separators in tests (on master)

- README.md
seems the `target` directory has been moved into the `assembly` directory
> Fix path of webapp-runner in readme

- main/src/main/java/webapp/runner/launch/Main.java
Users can set any connector attribute with `-ApropertyName=propertyValue`. Currently, if an unknown attribute name (or incompatible value type) is specified, the error is silently ignored. This leaves the user with no way of telling if the attribute was successfully set.
This PR adds user logging of the result of the `setProperty` call.
> Add setProperty() result logging

- assembly/pom.xml
- main/pom.xml
- memcached/pom.xml
- pom.xml
- redis/pom.xml
#194 did no include the required `-SNAPSHOT` suffix for unreleased versions.
> Add missing -SNAPSHOT suffix

- pom.xml
Plugin order in `pom.xml` determines execution order when plugins run in the same phase. `nexus-staging-maven-plugin` needs to run last to see the additional artefacts generated by other plugins.
> Fix plugin order

- assembly/pom.xml
- main/pom.xml
Documentation and source artifacts were not generated during the `deploy` phase for some submodules, causing Maven central to reject the release. This PR fixes this.
> Fix artifact generation for deploy

- .circleci/config.yml
- scripts/check-version.sh
By convention, this project's version number always starts with the version number of the embedded Tomcat server. This PR adds a CI check for this, allowing us to use dependabot without the risk of violating this convention. See #227 for some brief discussion.
Closes GUS-W-9802671
> Add CI check for version consistency

- main/src/main/java/webapp/runner/launch/CommandLineParams.java
- redis/src/main/java/webapp/runner/launch/RedisSessionStore.java
When using self-signed certificates, SSL endpoint validation will fail when the certificate is not present in the keystore. This PR adds the `--session-store-ssl-endpoint-identification` flag that allows users to disable SSL endpoint verification. By default, SSL endpoint validation is still enabled.
This is necessary for Heroku Redis which uses changing self-signed certificates.
Closes GUS-W-10292226
See https://github.com/heroku/webapp-runner/pull/253 for the 9.0 version of this PR
> Add --session-store-ssl-endpoint-identification

- pom.xml
I was a little too eager to remove some of the metadata from `pom.xml`. This PR re-adds missing metadata that is required to publish to Maven Central.
> Fix pom.xml for Maven Central release

- README.md
- webapp-runner-main/src/main/java/webapp/runner/launch/CommandLineParams.java
- webapp-runner-main/src/main/java/webapp/runner/launch/Main.java
There are special malicious request for which Tomcat usually logs stacktraces to the caller. Try a Null Code attack like https://XX.herokuapp.com/application/anything%00 . Tomcat will always answer it using the properties in the ErrorReportValve.
These requests aren't even dispatched to the deployed applications and thus error pages don't solve the problem.
This pull requests adds a new option to set the properties showReport and showServerInfo of ErrorReportValve to false.
Please also merge into tomcat9 branch
See https://help.heroku.com/tickets/1027939
> Added new command line parameter 'secure-error-report-valve'

- webapp-runner-redis/pom.xml
When the Redis store is used, we historically use the `FstCodec` which is deprecated. Redisson no longer includes the underlying dependency due to the deprecation so we need to add it manually. Ideally, we would stop using `FstCodec`, but that would mean that the data written to Redis previously would not be deserializable anymore. Since this is a very impactful breaking change, let's hold off until we migrate to Tomcat 10.
Ref: GUS-W-12671321
> Redis Session Storage: Add required `fst` dependency

- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
Continuation of #365, this PR adds the actual release. It also fixes some minor issues with the prepare release step I found after merging #365.
Ref: [GUS-W-14234076](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14234076)
> Add release workflow

- webapp-runner-10/CHANGELOG.md
I had to create a bogus release so that the release automation works correctly. It requires a "previous version" which doesn't exist for the first release. This PR fixes the CHANGELOG to point to the correct tag. The bogus release (and its tag) have already been removed.
> Fix webapp-runner-10 CHANGELOG

- .github/dependabot.yml
This project uses separate Maven projects for each supported Tomcat major version. These projects should never update the major version of Tomcat as we would create a new Maven project for such updates. 
This PR configures dependabot to ignore major version updates for Tomcat.
> Configure dependabot to ignore major Tomcat versions

- .github/workflows/release.yml
This is a follow-up fix to #491.
The correct output name is `token`, see:
https://github.com/actions/create-github-app-token/tree/v1/?tab=readme-ov-file#outputs
Spotted when working on another PR, since I have the GitHub Actions VSCode plugin installed, which lints the workflow files and highlights issues inline.
> Use correct output from `create-github-app-token`

- README.md
The `groupId` in both *pom.xml* files is `com.heroku`, which matches the published artifacts:
https://search.maven.org/search?q=g:com.heroku%20a:webapp-runner
This updates the documentation to match.
Note that there are no artifacts published under `com.github.heroku`:
https://search.maven.org/search?q=g:com.github.heroku
> Correct the groupId

- .github/workflows/release.yml
- webapp-runner-10/pom.xml
- webapp-runner-9/pom.xml
As of June 30, 2025 OSSRH has reached end of life and has been shut down. All OSSRH namespaces have been migrated to Central Publisher Portal.
This PR updates the release automation and Maven deploy configuration to use the new Central Publishing Portal API directly. We will not use the [OSSRH staging api](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/) which is a compatibility layer.
For users of this repository, nothing changes.
GUS-W-18961468
> Deploy to Central Publishing Portal

- webapp-runner-9/webapp-runner-main/pom.xml
- webapp-runner-9/webapp-runner-memcached/pom.xml
- webapp-runner-9/webapp-runner-redis/pom.xml
- webapp-runner-9/webapp-runner/pom.xml
The Central Publishing Portal enforces stricter component validation requirements compared to OSSRH. Following the changes introduced in #632, our current POM configuration no longer passes these validation checks.
This PR adjusts the POM configuration to meet the stricter validation requirements of the Central Publishing Portal.
This update specifically targets webapp-runner `9.x` only, as the repository is currently in transition between webapp-runner releases.
> Fix POM configuration for Central Publishing Portal validation
